"""Emit the Worker's copy of the extraction spec from the site's own source.

The prompt and schema must be byte-identical on both sides or the shared
endpoint quietly returns differently-shaped results than the BYO-key path.
Rather than keep two copies in sync by hand, this lifts them out of
ai_view.js and writes an ES module the Worker imports.
"""
import json
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "ai_view.js")
OUT = os.path.join(HERE, "..", "worker", "spec.generated.js")


def slice_decl(src, name):
    i = src.index(f"const {name} =")
    depth, j, started = 0, i, False
    while j < len(src):
        c = src[j]
        if c in "{[":
            depth += 1; started = True
        elif c in "}]":
            depth -= 1
        elif c == ";" and (not started or depth == 0):
            return src[i:j + 1]
        j += 1
    raise ValueError(name)


def main():
    src = open(SRC).read()
    decls = slice_decl(src, "AI_SCHEMA") + "\n" + slice_decl(src, "AI_SYSTEM")
    prog = decls + "\nprocess.stdout.write(JSON.stringify({SCHEMA: AI_SCHEMA, SYSTEM: AI_SYSTEM}));"
    out = subprocess.run(["node", "-e", prog], capture_output=True, text=True, check=True)
    spec = json.loads(out.stdout)
    with open(OUT, "w") as f:
        f.write("// GENERATED by scripts/build_worker_spec.py -- do not edit.\n"
                "// Source of truth: scripts/ai_view.js (AI_SYSTEM / AI_SCHEMA).\n"
                f"export const SYSTEM = {json.dumps(spec['SYSTEM'], ensure_ascii=False)};\n"
                f"export const SCHEMA = {json.dumps(spec['SCHEMA'], ensure_ascii=False, indent=2)};\n")
    print(f"wrote worker/spec.generated.js  (system {len(spec['SYSTEM'])} chars, "
          f"schema {len(json.dumps(spec['SCHEMA']))} bytes)")


if __name__ == "__main__":
    main()
